name: Package
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}

defaults:
  run:
    shell: bash

jobs:
  build-packages:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: dist-packages-${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement

      # Add your actual package building steps here
      - name: Build packages
        run: |
          # Add your build commands here
          mkdir -p dist
          echo "Package built" > dist/package.txt

      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.display-measurement.outputs.data-total-json }}' > total_energy_consumption_build.json

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-packages-${{ github.sha }}
          path: dist/

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-energy-consumption
          path: total_energy_consumption_build.json

  install-pkg:
    needs: build-packages
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macOS-14, windows-2022]
        pkg-name: [fabric, pytorch, lightning, notset]
        python-version: ["3.9", "3.11"]

    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v4
        with:
          name: dist-packages-${{ github.sha }}
          path: dist

      - name: Set package dir
        run: |
          python -c "print('PKG_DIR=' + {'notset': 'lightning'}.get('${{matrix.pkg-name}}', '${{matrix.pkg-name}}'))" >> $GITHUB_ENV

      - name: Install package - wheel & archive
        timeout-minutes: 25
        uses: ./.github/actions/pkg-install
        with:
          pkg-folder: dist/${{ env.PKG_DIR }}
          pkg-name: ${{ matrix.pkg-name }}

      - name: DocTests actions
        run: |
          pip install -q pytest -r requirements.txt
          python -m pytest assistant.py
        working-directory: .actions/

      - if: contains(fromJSON('["fabric", "pytorch"]'), matrix.pkg-name)
        name: Adjust code for standalone
        run: |
          python .actions/assistant.py copy_replace_imports --source_dir="./src" \
            --source_import="lightning.pytorch,lightning.fabric" \
            --target_import="pytorch_lightning,lightning_fabric"

      - name: Rename src folders
        run: |
          python -c "n = '${{matrix.pkg-name}}'; n = n if n in ('fabric', 'pytorch') else ''; print('PKG_NAME=' + n)" >> $GITHUB_ENV
          rm -f ./*/__*.py
          rm -f ./**/__*.py
          mv lightning lit
        working-directory: src/

      - if: ${{ matrix.pkg-name == 'lightning' || matrix.pkg-name == 'notset' }}
        name: Drop secondary doctest
        run: |
          items=("data")
          for item in "${items[@]}"; do
            echo "Removing $item"
            rm -rf $item
          done
        working-directory: src/lit

      - name: Install pytest doctest extension
        run: |
          pip install -q -r requirements/doctests.txt
          pip list

      - name: DocTest package
        env:
          LIGHTING_TESTING: 1
          PY_IGNORE_IMPORTMISMATCH: 1
        run: |
          python -m pytest src/lit/${PKG_NAME} --ignore-glob="**/cli/*-template/**" --doctest-plus

      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.display-measurement.outputs.data-total-json }}' > total_energy_consumption_${{ matrix.os }}_${{ matrix.pkg-name }}_${{ matrix.python-version }}.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: install-energy-consumption-${{ matrix.os }}-${{ matrix.pkg-name }}-${{ matrix.python-version }}
          path: total_energy_consumption_${{ matrix.os }}_${{ matrix.pkg-name }}_${{ matrix.python-version }}.json

  install-pkg-guardian:
    if: always()
    needs: install-pkg
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement

      - run: echo "${{ needs.install-pkg.result }}"

      - if: needs.install-pkg.result == 'failure'
        name: Failing...
        run: exit 1

      - if: contains(fromJSON('["cancelled", "skipped"]'), needs.install-pkg.result)
        name: Cancelled or Skipped
        run: sleep 90
        timeout-minutes: 2

      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.display-measurement.outputs.data-total-json }}' > total_energy_consumption_guardian.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: guardian-energy-consumption
          path: total_energy_consumption_guardian.json
