name: Test Fabric

on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}

defaults:
  run:
    shell: bash

jobs:
  fabric-cpu:
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.os }}
    env:
      DISABLE_MPS: ${{ matrix.os == 'macOS-14' && '1' || '0' }}
      FREEZE_REQUIREMENTS: ${{ !(github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}
      PACKAGE_NAME: ${{ matrix.pkg-name }}
      PYPI_CACHE_DIR: _pip-wheels
      TORCH_URL_STABLE: https://download.pytorch.org/whl/cpu/
      TORCH_URL_TEST: https://download.pytorch.org/whl/test/cpu/
    strategy:
      fail-fast: false
      matrix:
        include:
          # Add your matrix combinations here...
          - os: macOS-14
            pkg-name: lightning
            python-version: "3.10"
            pytorch-version: "2.1"
          # ... (full matrix continues as in your original)

    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version || '3.9' }}

      - name: Basic Setup
        run: pip install -q -r .actions/requirements.txt

      - id: measurement-4
        name: Record Measurement After basic setup
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: basic setup
          task: get-measurement

      - if: ${{ matrix.requires == 'oldest' }}
        name: Set min. dependencies
        run: |
          python .actions/assistant.py replace_oldest_ver
          pip install "cython<3.0" wheel
          pip install "pyyaml==5.4" --no-build-isolation

      - id: measurement-6
        name: Record Measurement After Set min. dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Set min. dependencies
          task: get-measurement

      - if: ${{ matrix.requires != 'oldest' }}
        name: Adjust PyTorch versions in requirements files
        run: |
          pip install -q -r requirements/ci.txt
          python -m wget https://raw.githubusercontent.com/Lightning-AI/utilities/main/scripts/adjust-torch-versions.py
          for fpath in $(ls requirements/**/*.txt); do
            python ./adjust-torch-versions.py "$fpath" "${{ matrix.pytorch-version }}"
          done

      - id: measurement-8
        name: Record Measurement After Adjust PyTorch versions
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Adjust PyTorch versions in requirements files
          task: get-measurement

      - name: pip wheels cache
        uses: actions/cache/restore@v4
        with:
          key: pypi_wheels
          path: ${{ env.PYPI_CACHE_DIR }}

      - run: |
          mkdir -p $PYPI_CACHE_DIR
          ls -lh $PYPI_CACHE_DIR

      - id: measurement-11
        name: Record Measurement After Step
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Step
          task: get-measurement

      - name: Expand Env. variables
        run: |
          echo "TORCH_URL=${{ matrix.pytorch-version == '2.7' && env.TORCH_URL_TEST || env.TORCH_URL_STABLE }}" >> $GITHUB_ENV
          echo "COVERAGE_SCOPE=${{ matrix.pkg-name == 'lightning' && 'lightning' || 'lightning_fabric' }}" >> $GITHUB_ENV
          echo "EXTRA_PREFIX=${{ matrix.pkg-name == 'lightning' && 'fabric-' || '' }}" >> $GITHUB_ENV

      - id: measurement-13
        name: Record Measurement After Expand Env. variables
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Expand Env. variables
          task: get-measurement

      - if: ${{ runner.os == 'macOS' }}
        name: Append Env. vars for MacOS
        run: echo "GLOO_SOCKET_IFNAME=lo0" >> $GITHUB_ENV

      - if: ${{ runner.os == 'windows' }}
        name: Append Env. vars for Windows
        run: echo "USE_LIBUV=0" >> $GITHUB_ENV

      - name: Install package & dependencies
        run: |
          pip install -e ".[${EXTRA_PREFIX}test,${EXTRA_PREFIX}strategies]" \
            -U --upgrade-strategy=eager --prefer-binary \
            --extra-index-url="${TORCH_URL}" --find-links="${PYPI_CACHE_DIR}"
          pip list
        timeout-minutes: 20

      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        continue-on-error: true
        name: Dump handy wheels
        uses: ./.github/actions/pip-wheels
        with:
          cache-key: pypi_wheels
          torch-url: ${{ env.TORCH_URL }}
          wheel-dir: ${{ env.PYPI_CACHE_DIR }}

      - if: ${{ matrix.pkg-name != 'lightning' }}
        name: Adjust tests
        run: |
          python .actions/assistant.py copy_replace_imports \
            --source_dir="./tests" \
            --source_import="lightning.fabric" \
            --target_import="lightning_fabric"

      - name: Testing Warnings
        run: python utilities/test_warnings.py
        working-directory: tests/tests_fabric

      - name: Testing Fabric
        run: |
          echo $GITHUB_RUN_ID
          python -m coverage run --source ${{ env.COVERAGE_SCOPE }} \
            -m pytest -v --timeout=60 --durations=50 --random-order-seed=$GITHUB_RUN_ID \
            --junitxml=junit.xml -o junit_family=legacy
        working-directory: tests/tests_fabric

      - if: success()
        name: Statistics
        run: |
          coverage report
          coverage xml
        working-directory: tests/tests_fabric

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          file: tests/tests_fabric/coverage.xml
          flags: ${{ env.COVERAGE_SCOPE }},cpu,pytest,python${{ matrix.python-version }}
          name: CPU-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true

      - name: Display Energy Results
        id: display-measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json

  fabric-cpu-guardian:
    if: always()
    needs: fabric-cpu
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement

      - run: echo "${{ needs.fabric-cpu.result }}"

      - if: needs.fabric-cpu.result == 'failure'
        name: failing...
        run: exit 1

      - if: contains(fromJSON('["cancelled", "skipped"]'), needs.fabric-cpu.result)
        name: cancelled or skipped...
        run: sleep 90
        timeout-minutes: 1

      - name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
