name: Update tutorials
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
jobs:
  docs-update:
    runs-on: ubuntu-22.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: initial state
        run: 'git submodule status

          # starting from second char as the line starts with +

          short_sha=$(git submodule status | grep -A 1 _notebooks | cut -c2-9)

          echo "SHA_ACTUAL=$short_sha" >> $GITHUB_ENV

          # Skip smudge - We''ll download binary files later in a faster batch

          git lfs install --skip-smudge

          '
      - id: measurement-3
        name: Record Measurement After initial state
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: initial state
          task: get-measurement
      - env:
          GIT_TRACE: 1
        name: update submodules
        run: 'git submodule sync

          git submodule update --remote --force

          '
      - id: measurement-5
        name: Record Measurement After update submodules
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: update submodules
          task: get-measurement
      - name: final state
        run: 'git submodule status

          git status

          # starting from second char as the line starts with +

          short_sha=$(git submodule status | grep -A 1 _notebooks | cut -c2-9)

          echo "SHA_LATEST=$short_sha" >> $GITHUB_ENV

          '
      - id: measurement-7
        name: Record Measurement After final state
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: final state
          task: get-measurement
      - if: ${{ github.event_name != 'pull_request' && env.SHA_ACTUAL != env.SHA_LATEST
          }}
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: _notebooks
          assignees: borda
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: "**This is automated update with the latest lighting tutorials!**\n\
            The target commit in the [publication](https://github.com/Lightning-AI/tutorials/tree/publication)\n\
            \ branch is [${{ env.SHA_LATEST }}](https://github.com/Lightning-AI/tutorials/commit/${{\
            \ env.SHA_LATEST }}).\n\nBefore proceeding further double check that the\
            \ PR include only submodule's head update. Eventually some additional\
            \ adjustments in lightning docs may be needed.\n"
          branch: docs/update-tutorials
          committer: GitHub <noreply@github.com>
          delete-branch: true
          labels: 'docs

            examples

            '
          title: 'docs: update ref to latest tutorials'
          token: ${{ secrets.PAT_GHOST }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
