name: Nightly packages
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
jobs:
  build-packages:
    env:
      PKG_NAME: lightning
    runs-on: ubuntu-22.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Convert actual version to nightly
        run: 'pip install -q -r .actions/requirements.txt

          python .actions/assistant.py convert_version2nightly

          '
      - id: measurement-4
        name: Record Measurement After Convert actual version to nightly
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Convert actual version to nightly
          task: get-measurement
      - run: python -c "print('NB_DIRS=' + str(2 if '${{ env.PKG_NAME }}' == 'pytorch'
          else 1))" >> $GITHUB_ENV
      - id: measurement-6
        name: Record Measurement After Step
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Step
          task: get-measurement
      - name: Build & check package
        uses: ./.github/actions/pkg-check
        with:
          allow-local-changes: 'true'
          nb-dirs: ${{ env.NB_DIRS }}
          pkg-name: ${{ env.PKG_NAME }}
      - uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: nightly-packages-${{ github.sha }}
          path: dist
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  publish-packages:
    env:
      PKG_NAME: lightning
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    needs: build-packages
    runs-on: ubuntu-22.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: nightly-packages-${{ github.sha }}
          path: dist
      - uses: ./.github/actions/pkg-publish
        with:
          pkg-folder: dist
          pypi-test-token: ${{ secrets[format('PYPI_TEST_TOKEN_{0}', env.PKG_NAME)]
            }}
      - uses: ./.github/actions/pkg-publish
        with:
          pkg-folder: dist
          pypi-token: ${{ secrets[format('PYPI_TOKEN_{0}', env.PKG_NAME)] }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
