name: Releasing packages
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
env:
  FREEZE_REQUIREMENTS: 1
  PYTHON_VER: '3.9'
  TORCH_URL: https://download.pytorch.org/whl/cpu/
jobs:
  build-packages:
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    uses: ./.github/workflows/_build-packages.yml
    with:
      artifact-name: dist-packages-${{ github.sha }}
  legacy-checkpoints:
    needs:
      - build-packages
    secrets: inherit
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    uses: ./.github/workflows/_legacy-checkpoints.yml
    with:
      create_pr: ${{ startsWith(github.event.ref, 'refs/tags') || github.event_name
        == 'release' }}
      push_to_s3: ${{ startsWith(github.event.ref, 'refs/tags') || github.event_name
        == 'release' }}
      upload_local: ${{ startsWith(github.event.ref, 'refs/tags') || github.event_name
        == 'release' }}
  pre-publish-packages:
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    needs: build-packages
    runs-on: ubuntu-22.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist-packages-${{ github.sha }}
          path: dist
      - id: folder
        name: Browse folder
        run: 'sudo apt install -q -y tree

          tree -L 2 -h dist/

          python -c "print(''pkg='' + ''${{ matrix.name }}''.lower())" >> $GITHUB_OUTPUT

          '
      - id: measurement-4
        name: Record Measurement After Browse folder
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Browse folder
          task: get-measurement
      - uses: ./.github/actions/pkg-publish
        with:
          pkg-folder: dist/${{ steps.folder.outputs.pkg }}
          pypi-test-token: ${{ secrets[format('PYPI_TEST_TOKEN_{0}', matrix.name)]
            }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        name:
          - FABRIC
          - PYTORCH
          - LIGHTNING
  publish-packages:
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    needs:
      - build-packages
    runs-on: ubuntu-22.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist-packages-${{ github.sha }}
          path: dist
      - id: folder
        name: Browse folder
        run: 'sudo apt install -q -y tree

          tree -L 2 -h dist/

          python -c "print(''pkg='' + ''${{ matrix.name }}''.lower())" >> $GITHUB_OUTPUT

          '
      - id: measurement-4
        name: Record Measurement After Browse folder
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Browse folder
          task: get-measurement
      - uses: ./.github/actions/pkg-publish
        with:
          pkg-folder: dist/${{ steps.folder.outputs.pkg }}
          pypi-token: ${{ secrets[format('PYPI_TOKEN_{0}', matrix.name)] }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        name:
          - FABRIC
          - PYTORCH
          - LIGHTNING
  release-version:
    outputs:
      tag: ${{ steps.lai-package.outputs.version }}
    runs-on: ubuntu-22.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: install Package
        run: 'pip install . --extra-index-url="${TORCH_URL}"

          pip list

          '
      - id: measurement-4
        name: Record Measurement After install Package
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: install Package
          task: get-measurement
      - id: lai-package
        name: package Version
        run: python -c "import lightning ; print(f'version={lightning.__version__}')"
          >> $GITHUB_OUTPUT
      - id: measurement-6
        name: Record Measurement After package Version
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: package Version
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  signaling:
    env:
      BRANCH_NAME: trigger/lightning-${{ needs.release-version.outputs.tag }}
      TAG: ${{ needs.release-version.outputs.tag }}
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    needs:
      - release-version
      - build-packages
    runs-on: ubuntu-22.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
        with:
          repository: gridai/base-images
          token: ${{ secrets.PAT_GHOST }}
      - name: Update lightning version
        run: "import json, os, re\ntag = os.getenv('TAG')\nfname_json = \"versions.json\"\
          \nwith open(fname_json, encoding=\"utf-8\") as fopen:\n    vers = json.load(fopen)\n\
          vers[\"lightning_version\"] = tag\nconda_ = vers[\"conda_snapshot\"].split(\"\
          .\")\nconda_[-1] = str(int(conda_[-1]) + 1)\nvers[\"conda_snapshot\"] =\
          \ \".\".join(conda_)\nwith open(fname_json, \"w\", encoding=\"utf-8\") as\
          \ fopen:\n    json.dump(vers, fopen, indent=2)\n    # satisfy pre-commit\
          \ with line fixer\n    fopen.write(os.linesep)\nfname_txt = \"conda-user/user-env-requirements.txt\"\
          \nwith open(fname_txt, encoding=\"utf-8\") as fopen:\n    reqs = fopen.read()\n\
          reqs = re.sub(r\"lightning\\w*==([\\d\\.]+)\", f\"lightning=={tag}\", reqs)\n\
          with open(fname_txt, \"w\", encoding=\"utf-8\") as fopen:\n    fopen.write(reqs)\n"
        shell: python
      - id: measurement-3
        name: Record Measurement After Update lightning version
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Update lightning version
          task: get-measurement
      - run: cat versions.json
      - id: measurement-5
        name: Record Measurement After Step
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Step
          task: get-measurement
      - if: github.event_name != 'pull_request'
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: 'versions.json

            conda-user/user-env-requirements.txt

            '
          assignees: 'justusschock

            borda

            '
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: '**This is automated update with the latest lighting [release](https://github.com/Lightning-AI/lightning/releases/tag/${{
            env.TAG }})!**

            Please, act swiftly to land this PR as it is effectively blocking lightning
            release to be finished...

            '
          branch: bump/lightning-${{ env.TAG }}
          commit-message: bumping lightning version -> (${{ env.TAG }})
          committer: GitHub <noreply@github.com>
          delete-branch: true
          reviewers: 'justusschock

            ethanwharris

            borda

            '
          title: Bump lightning ver `${{ env.TAG }}`
          token: ${{ secrets.PAT_GHOST }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  upload-packages:
    if: github.event_name == 'release'
    needs: build-packages
    runs-on: ubuntu-22.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist-packages-${{ github.sha }}
          path: dist
      - run: ls -lh dist/
      - id: measurement-4
        name: Record Measurement After Step
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Step
          task: get-measurement
      - name: Upload to release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: dist/*/*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
